// --- BEGIN: Helper data for phoneme parsing ---
// These lists are crucial for getPhonemeIDsFromSyllableIPA to accurately parse IPA strings.
// Ensure this list is comprehensive and matches the phonemes you expect to encounter.
const allRpPhonemes = [
	

        // --- RP Monophthongs (Long Vowels) ---
	{ ipa: 'iː', titleSuffix: "Long 'ee' sound (as in 'fleece')", theme: 'Vowel' },
	{ ipa: 'ɑː', titleSuffix: "Long 'ah' sound (as in 'start')", theme: 'Vowel' },
	{ ipa: 'ɔː', titleSuffix: "Long 'aw' sound (as in 'thought')", theme: 'Vowel' },
	{ ipa: 'uː', titleSuffix: "Long 'oo' sound (as in 'goose')", theme: 'Vowel' },
	{ ipa: 'ɜː', titleSuffix: "Long 'er' sound (as in 'nurse')", theme: 'Vowel' },
    { ipa: 'ɜːʳ', titleSuffix: "Long 'er' sound (as in 'nurse')rhotic! ", theme: 'Vowel'},
    // --- RP Diphthongs (Vowel Glides) ---
    { ipa: 'eɪ', titleSuffix: "Diphthong 'ay' sound (as in 'face')", theme: 'Diphthong' },
    { ipa: 'aɪ', titleSuffix: "Diphthong 'eye' sound (as in 'my')", theme: 'Diphthong' },
    { ipa: 'ɔɪ', titleSuffix: "Diphthong 'oy' sound (as in 'boy')", theme: 'Diphthong' },
    { ipa: 'əʊ', titleSuffix: "Diphthong 'oh' sound (as in 'goat')", theme: 'Diphthong' },
	{ ipa: 'oʊ', titleSuffix: "Diphthong 'oh' sound (as in 'goat')", theme: 'Diphthong' },
    { ipa: 'aʊ', titleSuffix: "Diphthong 'ow' sound (as in 'mouth')", theme: 'Diphthong' },
	{ ipa: 'ɪəʳ', titleSuffix: "Diphthong 'ear' sound (as in 'near')rhotic!", theme: 'Diphthong' },
	{ ipa: 'eəʳ', titleSuffix: "Diphthong 'air' sound (as in 'square')rhotic!", theme: 'Diphthong' },
	{ ipa: 'ʊəʳ', titleSuffix: "Diphthong 'ure' sound (as in 'cure')rhotic!", theme: 'Diphthong' },
	{ ipa: 'ɪə', titleSuffix: "Diphthong 'ear' sound (as in 'near')", theme: 'Diphthong' },
	{ ipa: 'eə', titleSuffix: "Diphthong 'air' sound (as in 'square')", theme: 'Diphthong' },
	{ ipa: 'ʊə', titleSuffix: "Diphthong 'ure' sound (as in 'cure')", theme: 'Diphthong' },
        // --- Consonants (Affricates) ---
    { ipa: 'tʃ', titleSuffix: "Voiceless 'ch' sound (as in 'church')", theme: 'Consonant' },
	{ ipa: 'dʒ', titleSuffix: "Voiced 'j' sound (as in 'judge')", theme: 'Consonant' },

    
	
	//THE FULL MONTY PHONEMES. ADDED TO FROM PHONEMES > 1 CHARACTER LONG (ABOVE)

  { "ipa": "p", "titleSuffix": "Voiceless bilabial plosive", "theme": "Consonant" },
  { "ipa": "t", "titleSuffix": "Voiceless alveolar plosive", "theme": "Consonant" },
  { "ipa": "b", "titleSuffix": "Voiced bilabial plosive", "theme": "Consonant" },
  { "ipa": "d", "titleSuffix": "Voiced alveolar plosive", "theme": "Consonant" },
  { "ipa": "ʈ", "titleSuffix": "Voiceless retroflex plosive", "theme": "Consonant" },
  { "ipa": "ɖ", "titleSuffix": "Voiced retroflex plosive", "theme": "Consonant" },
  { "ipa": "c", "titleSuffix": "Voiceless palatal plosive", "theme": "Consonant" },
  { "ipa": "ɟ", "titleSuffix": "Voiced palatal plosive", "theme": "Consonant" },
  { "ipa": "k", "titleSuffix": "Voiceless velar plosive", "theme": "Consonant" },
  { "ipa": "ɡ", "titleSuffix": "Voiced velar plosive", "theme": "Consonant" },
  { "ipa": "q", "titleSuffix": "Voiceless uvular plosive", "theme": "Consonant" },
  { "ipa": "ɢ", "titleSuffix": "Voiced uvular plosive", "theme": "Consonant" },
  { "ipa": "ʔ", "titleSuffix": "Glottal stop", "theme": "Consonant" },
  { "ipa": "m", "titleSuffix": "Bilabial nasal", "theme": "Consonant" },
  { "ipa": "ɱ", "titleSuffix": "Labiodental nasal", "theme": "Consonant" },
  { "ipa": "n", "titleSuffix": "Alveolar nasal", "theme": "Consonant" },
  { "ipa": "ɳ", "titleSuffix": "Retroflex nasal", "theme": "Consonant" },
  { "ipa": "ɲ", "titleSuffix": "Palatal nasal", "theme": "Consonant" },
  { "ipa": "ŋ", "titleSuffix": "Velar nasal", "theme": "Consonant" },
  { "ipa": "ɴ", "titleSuffix": "Uvular nasal", "theme": "Consonant" },
  { "ipa": "ʙ", "titleSuffix": "Bilabial trill", "theme": "Consonant" },
  { "ipa": "r", "titleSuffix": "Alveolar trill", "theme": "Consonant" },
  { "ipa": "ʀ", "titleSuffix": "Uvular trill", "theme": "Consonant" },
  { "ipa": "ⱱ", "titleSuffix": "Labiodental flap", "theme": "Consonant" },
  { "ipa": "ɾ", "titleSuffix": "Alveolar tap", "theme": "Consonant" },
  { "ipa": "ɽ", "titleSuffix": "Retroflex flap", "theme": "Consonant" },
  { "ipa": "ɸ", "titleSuffix": "Voiceless bilabial fricative", "theme": "Consonant" },
  { "ipa": "β", "titleSuffix": "Voiced bilabial fricative", "theme": "Consonant" },
  { "ipa": "f", "titleSuffix": "Voiceless labiodental fricative", "theme": "Consonant" },
  { "ipa": "v", "titleSuffix": "Voiced labiodental fricative", "theme": "Consonant" },
  { "ipa": "θ", "titleSuffix": "Voiceless dental fricative", "theme": "Consonant" },
  { "ipa": "ð", "titleSuffix": "Voiced dental fricative", "theme": "Consonant" },
  { "ipa": "s", "titleSuffix": "Voiceless alveolar sibilant", "theme": "Consonant" },
  { "ipa": "z", "titleSuffix": "Voiced alveolar sibilant", "theme": "Consonant" },
  { "ipa": "ʃ", "titleSuffix": "Voiceless postalveolar sibilant", "theme": "Consonant" },
  { "ipa": "ʒ", "titleSuffix": "Voiced postalveolar sibilant", "theme": "Consonant" },
  { "ipa": "ʂ", "titleSuffix": "Voiceless retroflex sibilant", "theme": "Consonant" },
  { "ipa": "ʐ", "titleSuffix": "Voiced retroflex sibilant", "theme": "Consonant" },
  { "ipa": "ç", "titleSuffix": "Voiceless palatal fricative", "theme": "Consonant" },
  { "ipa": "ʝ", "titleSuffix": "Voiced palatal fricative", "theme": "Consonant" },
  { "ipa": "x", "titleSuffix": "Voiceless velar fricative", "theme": "Consonant" },
  { "ipa": "ɣ", "titleSuffix": "Voiced velar fricative", "theme": "Consonant" },
  { "ipa": "χ", "titleSuffix": "Voiceless uvular fricative", "theme": "Consonant" },
  { "ipa": "ʁ", "titleSuffix": "Voiced uvular fricative", "theme": "Consonant" },
  { "ipa": "ħ", "titleSuffix": "Voiceless pharyngeal fricative", "theme": "Consonant" },
  { "ipa": "ʕ", "titleSuffix": "Voiced pharyngeal fricative", "theme": "Consonant" },
  { "ipa": "h", "titleSuffix": "Voiceless glottal fricative", "theme": "Consonant" },
  { "ipa": "ɦ", "titleSuffix": "Voiced glottal fricative", "theme": "Consonant" },
  { "ipa": "ɬ", "titleSuffix": "Voiceless lateral alveolar fricative", "theme": "Consonant" },
  { "ipa": "ɮ", "titleSuffix": "Voiced lateral alveolar fricative", "theme": "Consonant" },
  { "ipa": "ʋ", "titleSuffix": "Labiodental approximant", "theme": "Consonant" },
  { "ipa": "ɹ", "titleSuffix": "Alveolar approximant", "theme": "Consonant" },
  { "ipa": "ɻ", "titleSuffix": "Retroflex approximant", "theme": "Consonant" },
  { "ipa": "j", "titleSuffix": "Palatal approximant", "theme": "Consonant" },
  { "ipa": "ɰ", "titleSuffix": "Velar approximant", "theme": "Consonant" },
  { "ipa": "l", "titleSuffix": "Alveolar lateral approximant", "theme": "Consonant" },
  { "ipa": "ɭ", "titleSuffix": "Retroflex lateral approximant", "theme": "Consonant" },
  { "ipa": "ʎ", "titleSuffix": "Palatal lateral approximant", "theme": "Consonant" },
  { "ipa": "ʟ", "titleSuffix": "Velar lateral approximant", "theme": "Consonant" },
  { "ipa": "ʘ", "titleSuffix": "Bilabial click", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ǀ", "titleSuffix": "Dental click", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ǃ", "titleSuffix": "Alveolar click", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ǂ", "titleSuffix": "Palatal click", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ǁ", "titleSuffix": "Alveolar lateral click", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ɓ", "titleSuffix": "Voiced bilabial implosive", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ɗ", "titleSuffix": "Voiced dental/alveolar implosive", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ʄ", "titleSuffix": "Voiced palatal implosive", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ɠ", "titleSuffix": "Voiced velar implosive", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "ʛ", "titleSuffix": "Voiced uvular implosive", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "pʼ", "titleSuffix": "Bilabial ejective", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "tʼ", "titleSuffix": "Alveolar ejective", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "kʼ", "titleSuffix": "Velar ejective", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "sʼ", "titleSuffix": "Alveolar ejective fricative", "theme": "Non-Pulmonic Consonant" },
  { "ipa": "i", "titleSuffix": "Close front unrounded vowel", "theme": "Vowel" },
  { "ipa": "y", "titleSuffix": "Close front rounded vowel", "theme": "Vowel" },
  { "ipa": "ɨ", "titleSuffix": "Close central unrounded vowel", "theme": "Vowel" },
  { "ipa": "ʉ", "titleSuffix": "Close central rounded vowel", "theme": "Vowel" },
  { "ipa": "ɯ", "titleSuffix": "Close back unrounded vowel", "theme": "Vowel" },
  { "ipa": "u", "titleSuffix": "Close back rounded vowel", "theme": "Vowel" },
  { "ipa": "ɪ", "titleSuffix": "Near-close near-front unrounded vowel", "theme": "Vowel" },
  { "ipa": "ʏ", "titleSuffix": "Near-close near-front rounded vowel", "theme": "Vowel" },
  { "ipa": "ʊ", "titleSuffix": "Near-close near-back rounded vowel", "theme": "Vowel" },
  { "ipa": "e", "titleSuffix": "Close-mid front unrounded vowel", "theme": "Vowel" },
  { "ipa": "ø", "titleSuffix": "Close-mid front rounded vowel", "theme": "Vowel" },
  { "ipa": "ɘ", "titleSuffix": "Close-mid central unrounded vowel", "theme": "Vowel" },
  { "ipa": "ɵ", "titleSuffix": "Close-mid central rounded vowel", "theme": "Vowel" },
  { "ipa": "ɤ", "titleSuffix": "Close-mid back unrounded vowel", "theme": "Vowel" },
  { "ipa": "o", "titleSuffix": "Close-mid back rounded vowel", "theme": "Vowel" },
  { "ipa": "ɛ", "titleSuffix": "Open-mid front unrounded vowel", "theme": "Vowel" },
  { "ipa": "œ", "titleSuffix": "Open-mid front rounded vowel", "theme": "Vowel" },
  { "ipa": "ɜ", "titleSuffix": "Open-mid central unrounded vowel", "theme": "Vowel" },
  { "ipa": "ɞ", "titleSuffix": "Open-mid central rounded vowel", "theme": "Vowel" },
  { "ipa": "ʌ", "titleSuffix": "Open-mid back unrounded vowel", "theme": "Vowel" },
  { "ipa": "ɔ", "titleSuffix": "Open-mid back rounded vowel", "theme": "Vowel" },
  { "ipa": "æ", "titleSuffix": "Near-open front unrounded vowel", "theme": "Vowel" },
  { "ipa": "ɐ", "titleSuffix": "Near-open central vowel", "theme": "Vowel" },
  { "ipa": "a", "titleSuffix": "Open front unrounded vowel", "theme": "Vowel" },
  { "ipa": "ɶ", "titleSuffix": "Open front rounded vowel", "theme": "Vowel" },
  { "ipa": "ɑ", "titleSuffix": "Open back unrounded vowel", "theme": "Vowel" },
  { "ipa": "ɒ", "titleSuffix": "Open back rounded vowel", "theme": "Vowel" },
  { "ipa": "ʍ", "titleSuffix": "Voiceless labial-velar fricative", "theme": "Consonant" },
  { "ipa": "w", "titleSuffix": "Voiced labial-velar approximant", "theme": "Consonant" },
  { "ipa": "ɥ", "titleSuffix": "Voiced labial-palatal approximant", "theme": "Consonant" },
  { "ipa": "ʜ", "titleSuffix": "Voiceless epiglottal fricative", "theme": "Consonant" },
  { "ipa": "ʢ", "titleSuffix": "Voiced epiglottal fricative", "theme": "Consonant" },
  { "ipa": "ʡ", "titleSuffix": "Epiglottal stop", "theme": "Consonant" },
  { "ipa": "ɕ", "titleSuffix": "Voiceless alveolo-palatal sibilant", "theme": "Consonant" },
  { "ipa": "ʑ", "titleSuffix": "Voiced alveolo-palatal sibilant", "theme": "Consonant" },
  { "ipa": "ɺ", "titleSuffix": "Alveolar lateral flap", "theme": "Consonant" },
  { "ipa": "ɧ", "titleSuffix": "Velar-palatal fricative", "theme": "Consonant" },
  { "ipa": "ə", "titleSuffix": "Schwa sound (as in 'about', unstressed)", "theme": 'Vowel' }

]
const knownThreeCharPhonemes = allRpPhonemes.filter(p => p.ipa.length === 3).map(p => p.ipa).sort((a, b) => b.length - a.length);
const knownTwoCharPhonemes = allRpPhonemes.filter(p => p.ipa.length === 2).map(p => p.ipa).sort((a, b) => b.length - a.length);
const knownSingleCharPhonemes = allRpPhonemes.filter(p => p.ipa.length === 1).map(p => p.ipa);

module.exports = {
  allRpPhonemes,
  knownThreeCharPhonemes,
  knownTwoCharPhonemes,
  knownSingleCharPhonemes
  
};